### ISSUE TITLE
Small suggestion: separate saved_data and experiments from this repo

### ISSUE THREAD

**Issue by Steve-Tod** [utiasSTARS/bingham-rotation-learning#2]
Hi, thanks for your code! I have a small suggestion: separating the saved_data folder from this repo. For example you can move the data and pre-trained models to Google Drive. I received 421MB data during `git clone`😂

**Comment by valentinp** [comment]
You're totally right - sorry about that! I pruned the repo (including commit history) of any large files and moved several experiment files to Drive. Repo should now be about ~20mb to clone. Thank!
