### ISSUE TITLE
RuntimeError: Assertion `src->dim() == 2' failed

### ISSUE THREAD

**Issue by nematoli** [utiasSTARS/bingham-rotation-learning#3]
Hi!

When I input a tensor of shape Bx4x4 into torch.symeig(A, eigenvectors=True), I get the following error:

RuntimeError: Assertion `src->dim() == 2' failed.  at /pytorch/aten/src/THC/generic/THCTensorMathMagma.cu:42

I am using torch version 1.1.0. Do you have any idea why this happens?

**Comment by kkoledic1212** [comment]
Have you perhaps found the solution to this problem?
